apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: /mnt/database/
    server: 10.0.0.2
